### ISSUE TITLE
Problem with rootprobs_phydyn.xml example

### ISSUE THREAD

**Issue by adamallo** [mrc-ide/PhyDyn#5]
I am getting the following error when I run the example file rootprobs_phydyn.xml, replicated with BEAST 2.5.0 in Mac and 2.5.2 in Linux. In both cases I am using the latest version of PhyDyn installed using BEAST2's packagemanager.
` Random number seed: 1554775524030

File: rootprobs_phydyn.xml seed: 1554775524030 threads: 1
inv3loc_0: 2 4
inv4loc_1: 2 4
inv5loc_1: 2 4
inv6loc_1: 2 4
inv2loc_0: 2 4
inv1loc_0: 2 4
Alignment(sequences)
  6 taxa
  2 sites
  1 patterns

Warning: Unknown variable name IX in population parameters object
model-name = simplemodel;
definitions = {
  gamma01 = m10*I1/I0;
  gamma10 = m01*I0/I1;
}
equations = {
  F(I0,I0) = 100*I0/2;
  F(I1,I1) = 100*I1/2;
  G(I0,I1) = gamma01*I0;
  G(I1,I0) = gamma10*I1;
  D(I0) = 100*I0/2-gamma01*I0+gamma10*I1;
  D(I1) = 100*I1/2-gamma10*I1+gamma01*I0;
  dot(S) = 0;
}
model-parameters = {
  m10 = 0.01;
  dummy = 5.0;
  m01 = 0.001;
}
trajectory-parameters = {
  t0 = -0.1
  method=classicrk; integrationSteps=1001;
  initial-vales = {
    I0 = 50.0;
    I1 = 25.0;
    S = 100.0;
  };
}
===============================================================================
Citations for this model:

Bouckaert RR, Heled J, Kuehnert D, Vaughan TG, Wu C-H, Xie D, Suchard MA,
  Rambaut A, Drummond AJ (2014) BEAST 2: A software platform for Bayesian
  evolutionary analysis. PLoS Computational Biology 10(4): e1003537

Volz EM, Siveroni I. 2018. Bayesian phylodynamic inference with complex models.
  PLos Computational Biology. 14(11), ISSN:1553-7358

===============================================================================
Start likelihood: -147.55053790038968
Writing file rootStateProbabilities_phydyn.log
Trying to write file rootStateProbabilities_phydyn.log but the file already exists (perhaps use the -overwrite flag?).
Overwrite (Y/N)?:
Y
Writing file rootStateProbabilities_phydyn.log
         Sample      posterior
Fatal exception: 11
java.lang.ArrayIndexOutOfBoundsException: 11
	at phydyn.distribution.StateProbabilitiesVectors.getRootProbs(Unknown Source)
	at phydyn.loggers.STreeRootLogger.log(Unknown Source)
	at beast.core.Loggable.log(Unknown Source)
	at beast.core.Logger.log(Unknown Source)
	at beast.core.MCMC.log(Unknown Source)
	at beast.core.MCMC.propagateState(Unknown Source)
	at beast.core.MCMC.doLoop(Unknown Source)
	at beast.core.MCMC.run(Unknown Source)
	at beast.app.BeastMCMC.run(Unknown Source)
	at beast.app.beastapp.BeastMain.<init>(Unknown Source)
	at beast.app.beastapp.BeastMain.main(Unknown Source)
Fatal exception: 11
java.lang.RuntimeException: An error was encounted. Terminating BEAST
	at beast.app.util.ErrorLogHandler.publish(Unknown Source)
	at java.util.logging.Logger.log(Logger.java:738)
	at java.util.logging.Logger.doLog(Logger.java:765)
	at java.util.logging.Logger.log(Logger.java:788)
	at java.util.logging.Logger.severe(Logger.java:1464)
	at beast.app.beastapp.BeastMain.<init>(Unknown Source)
	at beast.app.beastapp.BeastMain.main(Unknown Source) `

**Comment by igococha** [comment]
Solved. version 1.3.3
