### ISSUE TITLE
Problem following Tutorial SIR2 Treelikelihood

### ISSUE THREAD

**Issue by adamallo** [mrc-ide/PhyDyn#7]
The current version of the tutorial SIR2 Treelikelihood cannot be followed properly due to:

1. sir2Master.xml is missing from the repository
2. Modifying the provided sir2TrajectoryFinal0.xml using it together with sir2Master.nwk generates the following problem (tested with BEAST 2.5.0 in Mac and 2.5.2 in Linux. In both cases I am using the latest version of PhyDyn installed using BEAST2's packagemanager)

`File: sir2Trajectory_final.xml seed: 1554771653242 threads: 1
Generating Likelihood test xml
output xml file = sir2Likelihood.xml
--- tree file: sir2Master.nwk
root height: 13.225650562640002
num tips = 200
-- Population model
model-name = twodeme;
definitions = {
  k0 = beta0*S;
  k1 = beta1*S;
}
equations = {
  F(I0,I0) = k0*I0;
  F(I1,I0) = k1*I1;
  G(I0,I1) = gamma0*I0;
  D(I0) = 0;
  D(I1) = gamma1*I1;
  dot(S) = b*S-(beta0*I0+beta1*I1)*S;
}
model-parameters = {
  beta0 = 0.001;
  beta1 = 1.0E-4;
  gamma0 = 1.0;
  gamma1 = 0.1111;
  b = 0.01;
}
trajectory-parameters = {
  t0 = 0.0 t1 = 20.0
  method=classicrk; integrationSteps=1001;
  initial-vales = {
    I0 = 1.0;
    I1 = 0.0;
    S = 999.0;
  };
}
Fatal exception: null
java.lang.NullPointerException
	at phydyn.model.ModelParameters.writeXML(Unknown Source)
	at phydyn.model.PopModelODE.writeXML(Unknown Source)
	at phydyn.run.XMLGenerator.writeLikelihood(Unknown Source)
	at phydyn.run.XMLGenerator.run(Unknown Source)
	at beast.app.BeastMCMC.run(Unknown Source)
	at beast.app.beastapp.BeastMain.<init>(Unknown Source)
	at beast.app.beastapp.BeastMain.main(Unknown Source)
Fatal exception: null
java.lang.RuntimeException: An error was encounted. Terminating BEAST
	at beast.app.util.ErrorLogHandler.publish(Unknown Source)
	at java.util.logging.Logger.log(Logger.java:738)
	at java.util.logging.Logger.doLog(Logger.java:765)
	at java.util.logging.Logger.log(Logger.java:788)
	at java.util.logging.Logger.severe(Logger.java:1463)
	at beast.app.beastapp.BeastMain.<init>(Unknown Source)
	at beast.app.beastapp.BeastMain.main(Unknown Source)

`

**Comment by igococha** [comment]
Solved with version 1.3.3
